# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropySingle <- function(p) {
    .Call(`_DIBmix_entropySingle`, p)
}

klSingle <- function(p, q) {
    .Call(`_DIBmix_klSingle`, p, q)
}

vlog <- function(x) {
    .Call(`_DIBmix_vlog`, x)
}

qt_x_step_cpp <- function(n_rows, T, beta, py_x, qy_t, qt) {
    .Call(`_DIBmix_qt_x_step_cpp`, n_rows, T, beta, py_x, qy_t, qt)
}

qt_x_step_beta_cpp <- function(n_rows, T, py_x, qy_t, qt, qt_x) {
    .Call(`_DIBmix_qt_x_step_beta_cpp`, n_rows, T, py_x, qy_t, qt, qt_x)
}

qy_t_step_cpp <- function(py_x, qt_x, qt, px) {
    .Call(`_DIBmix_qy_t_step_cpp`, py_x, qt_x, qt, px)
}

